# Usage: cmake -DIN=<file> -DOUT=<header> -DNAME=<symbol> -P bin2h.cmake
# alignas(4): vkCreateShaderModule reads the SPIR-V array as uint32_t words.

if(NOT IN OR NOT OUT OR NOT NAME)
    message(FATAL_ERROR "bin2h.cmake needs -DIN=, -DOUT=, -DNAME=")
endif()

file(READ "${IN}" _hex HEX)
string(LENGTH "${_hex}" _hexlen)
math(EXPR _bytes "${_hexlen} / 2")

# wrap 16 per line for readable diffs.
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _arr "${_hex}")
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n    " _arr "${_arr}")

get_filename_component(_in_name "${IN}" NAME)
file(WRITE "${OUT}"
"// Generated by tools/cmake/bin2h.cmake from ${_in_name} -- do not edit.
#pragma once

#include <cstddef>

alignas(4) inline constexpr unsigned char ${NAME}[] = {
    ${_arr}
};
inline constexpr std::size_t ${NAME}_size = ${_bytes};
")
